version: "2.1"

services:
    base_db:
        container_name: base_db
        image: "mysql:8.0"
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME} 
        ports:
            - "3306:3306"
        volumes:
            # - ./ext.sql:/docker-entrypoint-initdb.d/ext.sql
            # - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            - ./dbdata:/var/lib/mysql/:delegated
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 10s
            retries: 10

    base_backend:
        container_name: base_backend
        build:
            context: ../backend
            dockerfile: ../docker/dockerfiles/backend
        volumes:
            - ../backend:/code:delegated
            - ./php.conf:/usr/local/etc/php/conf.d
              # - /code/vendor
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - PYTHONPATH=/code/
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - EMAIL_ENABLE=${EMAIL_ENABLE}

            - APP_TITLE=${APP_TITLE}
            - APP_DESCRTIPTION=%{APP_DESCRTIPTION}

            - PORT=${PORT}
            - PROTOCOL=${PROTOCOL}
            - DOMAIN=${DOMAIN}

            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_HOST=base_db
            - DB_PORT=5432
            - DB_TEST=base_test

            - EMAIL_DOMAIN=${EMAIL_DOMAIN}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - EMAIL_USE_TLS=${EMAIL_USE_TLS}
        ports:
            - "8000:8000"
            - "9000:9000"
        depends_on:
            base_db:
                condition: service_healthy
        tty: ${DOCKER_TTY}
        command: ${DOCKER_COMMAND}

    base_frontend:
      container_name: base_frontend 
      build:
        context: ../frontend
        dockerfile: ../docker/dockerfiles/frontend
      volumes:
        - ../frontend:/code:delegated
        - /code/node_modules
      tty: ${DOCKER_TTY}

    base_nginx:
        container_name: base_nginx
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d
            - ${SSL_PATH}:/resource/ssl
            - ../backend/public/:/resource/public
        ports:
            - "443:443"
        depends_on:
            - base_backend
